WORKFLOWS = {
    'delegation': {
        'label': 'Delegation Request',
        'short_label': 'Delegation',
        'kicker': 'FULFILLMENT / OWNER APPROVED',
        'description': 'Grant Full Access after mailbox-owner authorization, then verify propagation and user access.',
        'incident': {
            'number': 'RITM0042819',
            'type': 'Service Request',
            'priority': 'P3 - Moderate',
            'state': 'New',
            'created': '14:32:08 UTC',
            'assignment_group': 'Messaging Operations',
            'summary': 'Full Access required for Finance Operations shared mailbox',
            'mailbox': 'finance.operations@contoso.com',
            'requester': 'Avery Morgan',
            'requester_upn': 'avery.morgan@contoso.com',
            'owner': 'Priya Shah',
            'permission': 'Full Access',
            'target_sla': '60 min',
        },
        'run': {
            'id': 'RUN-DLG-8F31C2',
            'correlation_id': 'corr-7b31-418f-a920',
            'policy': 'SMB-DELEGATION-v3.4',
            'risk': 'Medium',
        },
        'stages': [
            {'id': 'trigger', 'label': 'Trigger'},
            {'id': 'intake', 'label': 'Intake'},
            {'id': 'reason', 'label': 'Reason'},
            {'id': 'secure', 'label': 'Secure'},
            {'id': 'approve', 'label': 'Approve'},
            {'id': 'execute', 'label': 'Execute'},
            {'id': 'validate', 'label': 'Validate'},
            {'id': 'resolve', 'label': 'Resolve'},
        ],
        'steps': [
            {
                'id': 'snow-event',
                'stage': 'trigger',
                'agent': 'Integration Layer',
                'title': 'ServiceNow event accepted',
                'summary': 'Logic Apps validates the webhook signature and places an immutable event on the mailbox-agent queue.',
                'skill': 'servicenow_event_listener',
                'system': 'ServiceNow',
                'connector': 'Logic Apps + Service Bus',
                'duration': '184 ms',
                'command': 'POST /events/servicenow/v1/requests',
                'request': {'sys_id': '7f2c91d5db43a110', 'number': 'RITM0042819', 'event': 'request.created'},
                'response': {'accepted': True, 'queue': 'mailbox-operations-prod', 'sequence': 18442},
                'evidence': ['HMAC signature verified', 'Schema contract v1.8 passed', 'Queue delivery acknowledged'],
                'policy': {'identity': 'svc-snow-webhook', 'authorization': 'event.ingest', 'data_class': 'Internal'},
            },
            {
                'id': 'ticket-intake',
                'stage': 'intake',
                'agent': 'ServiceNow Agent',
                'title': 'Ticket claimed and normalized',
                'summary': 'The intake agent locks the request, assigns Messaging Operations, and extracts mailbox, user, and permission fields.',
                'skill': 'intent_classification',
                'system': 'ServiceNow',
                'connector': 'ServiceNow MCP Server',
                'duration': '436 ms',
                'command': 'PATCH /api/now/table/sc_req_item/7f2c91d5db43a110',
                'request': {'assigned_to': 'Shared Mailbox Agent', 'state': 'Work in Progress', 'lock_ttl': 'PT15M'},
                'response': {'updated': True, 'version': 7, 'required_fields': '8/8'},
                'evidence': ['Exclusive processing lock acquired', 'Assignment rule MSG-AUTO-04 matched', 'Required fields complete'],
                'policy': {'identity': 'mi-mailbox-agent-prod', 'authorization': 'ticket.write', 'data_class': 'Internal'},
            },
            {
                'id': 'classify',
                'stage': 'reason',
                'agent': 'LLM Ticket Classifier',
                'title': 'Delegation intent classified',
                'summary': 'Azure OpenAI maps the request to the owner-approved delegation workflow and extracts Full Access as the requested entitlement.',
                'skill': 'classify_and_extract',
                'system': 'Azure OpenAI',
                'connector': 'Private Endpoint',
                'duration': '712 ms',
                'command': 'responses.create(model=gpt-4.1, schema=MailboxIntent)',
                'request': {'ticket': 'RITM0042819', 'taxonomy': 'shared_mailbox.v3', 'redaction': 'enabled'},
                'response': {'intent': 'shared_mailbox.delegation.add', 'confidence': 0.98, 'approval_required': True},
                'evidence': ['Structured output schema valid', 'Confidence above 0.85 threshold', 'No restricted data detected'],
                'policy': {'identity': 'mi-agent-runtime', 'authorization': 'aoai.inference', 'data_class': 'Internal'},
            },
            {
                'id': 'plan',
                'stage': 'reason',
                'agent': 'Root Agent',
                'title': 'Execution plan checkpointed',
                'summary': 'The orchestrator builds an allowlisted plan with two human control points and persists resumable state.',
                'skill': 'plan_workflow',
                'system': 'Agent Runtime',
                'connector': 'Microsoft Agent Framework',
                'duration': '96 ms',
                'command': 'orchestrator.plan(policy="SMB-DELEGATION-v3.4")',
                'request': {'intent': 'shared_mailbox.delegation.add', 'permission': 'FullAccess', 'approval_required': True},
                'response': {'steps': 9, 'gates': 2, 'checkpoint': 'cp-001', 'rollback': 'permission_remove'},
                'evidence': ['All skills found in allowlist', 'Rollback action registered', 'Checkpoint cp-001 committed'],
                'policy': {'identity': 'root-agent', 'authorization': 'workflow.execute', 'data_class': 'Internal'},
            },
            {
                'id': 'pim',
                'stage': 'secure',
                'agent': 'Remediation Agent',
                'title': 'Exchange role activated',
                'summary': 'The remediation identity activates its eligible Exchange Administrator role with a ticket-bound justification.',
                'skill': 'pim_activate',
                'system': 'Microsoft Entra',
                'connector': 'Microsoft Graph',
                'duration': '3.2 s',
                'command': 'POST /roleManagement/directory/roleAssignmentScheduleRequests',
                'request': {'role': 'Exchange Administrator', 'duration': 'PT1H', 'justification': 'RITM0042819'},
                'response': {'status': 'Provisioned', 'expires': '15:35 UTC', 'mfa': 'satisfied'},
                'evidence': ['Eligible assignment verified', 'MFA claim present', 'Activation audit ID PIM-88421'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'eligible role', 'data_class': 'Privileged'},
            },
            {
                'id': 'mailbox-check',
                'stage': 'execute',
                'agent': 'Remediation Agent',
                'title': 'Mailbox and delegation validated',
                'summary': 'Exchange confirms an active shared mailbox, resolves its owner, and verifies that the requested delegate is not already assigned.',
                'skill': 'mailbox_status_check',
                'system': 'Exchange Online',
                'connector': 'M365 MCP Server',
                'duration': '1.4 s',
                'command': 'Get-EXOMailbox + Get-EXOMailboxPermission',
                'request': {'identity': 'finance.operations@contoso.com', 'user': 'avery.morgan@contoso.com'},
                'response': {'recipient_type': 'SharedMailbox', 'account_disabled': True, 'owner': 'priya.shah@contoso.com', 'existing_access': False},
                'evidence': ['Recipient type is SharedMailbox', 'Mailbox is licensed correctly', 'No duplicate ACE found'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'exchange.read', 'data_class': 'Confidential'},
            },
            {
                'id': 'owner-approval',
                'stage': 'approve',
                'agent': 'Approval Manager',
                'title': 'Owner authorization requested',
                'summary': 'The workflow checkpoints before mutation and sends the mailbox owner a ticket-bound Teams approval card.',
                'skill': 'owner_approval_gate',
                'system': 'Teams / Copilot Studio',
                'connector': 'Microsoft Graph',
                'duration': 'Human response',
                'command': 'POST /teams/approvals/adaptiveCards',
                'request': {'approver': 'priya.shah@contoso.com', 'permission': 'FullAccess', 'expires_in': 'PT8H'},
                'response': {'state': 'Awaiting decision', 'approval_id': 'APR-10981', 'checkpoint': 'cp-002'},
                'evidence': ['Owner resolved from authoritative record', 'Request hash attached', 'Execution paused at cp-002'],
                'policy': {'identity': 'approval-manager', 'authorization': 'approval.request', 'data_class': 'Confidential'},
                'gate': {
                    'kind': 'owner',
                    'eyebrow': 'HUMAN CONTROL POINT 1 OF 2',
                    'title': 'Mailbox owner approval',
                    'message': 'Priya Shah is authorizing Full Access for Avery Morgan on Finance Operations.',
                    'recipient': 'Priya Shah / Mailbox Owner',
                    'channel': 'Teams adaptive card / APR-10981',
                    'primary': 'Approve request',
                    'secondary': 'Reject and escalate',
                },
            },
            {
                'id': 'permission-apply',
                'stage': 'execute',
                'agent': 'Remediation Agent',
                'title': 'Full Access permission applied',
                'summary': 'The approved, allowlisted Exchange command adds the delegate and enables Outlook Auto-Mapping.',
                'skill': 'permission_apply',
                'system': 'Exchange Online',
                'connector': 'Exchange PowerShell via MCP',
                'duration': '2.1 s',
                'command': 'Add-MailboxPermission -AccessRights FullAccess -AutoMapping $true',
                'request': {'identity': 'finance.operations@contoso.com', 'user': 'avery.morgan@contoso.com', 'access_rights': ['FullAccess'], 'automapping': True},
                'response': {'applied': True, 'is_inherited': False, 'deny': False, 'change_id': 'EXO-772910'},
                'evidence': ['Approval APR-10981 verified', 'Command parameters matched allowlist', 'Exchange change ID captured'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'exchange.write.scoped', 'data_class': 'Privileged'},
            },
            {
                'id': 'permission-verify',
                'stage': 'validate',
                'agent': 'Outcome Verifier',
                'title': 'Permission state verified',
                'summary': 'A separate read verifies the explicit allow entry and compares the result with the approved request.',
                'skill': 'permission_verify',
                'system': 'Exchange Online',
                'connector': 'M365 MCP Server',
                'duration': '892 ms',
                'command': 'Get-EXOMailboxPermission -Identity finance.operations@contoso.com',
                'request': {'expected_user': 'avery.morgan@contoso.com', 'expected_right': 'FullAccess'},
                'response': {'matched': True, 'access_rights': ['FullAccess'], 'deny': False, 'confidence': 1.0},
                'evidence': ['Independent read-after-write passed', 'Requested and actual rights match', 'No conflicting deny entry'],
                'policy': {'identity': 'outcome-verifier', 'authorization': 'exchange.read', 'data_class': 'Confidential'},
            },
            {
                'id': 'replication',
                'stage': 'validate',
                'agent': 'Remediation Agent',
                'title': 'Delegation propagation monitored',
                'summary': 'The workflow releases its worker, persists the wake-up time, and probes Exchange until the permission is effective.',
                'skill': 'replication_wait',
                'system': 'Agent Runtime',
                'connector': 'Durable checkpoint',
                'duration': '20 min policy',
                'delay': 1700,
                'command': 'wait.until(permission_effective, interval="PT2M", timeout="PT20M")',
                'request': {'change_id': 'EXO-772910', 'probe_interval': 'PT2M', 'timeout': 'PT20M'},
                'response': {'effective': True, 'probes': 3, 'elapsed': 'PT6M12S', 'checkpoint': 'cp-003'},
                'evidence': ['Worker released during wait', 'Three propagation probes recorded', 'Effective state confirmed'],
                'policy': {'identity': 'root-agent', 'authorization': 'workflow.resume', 'data_class': 'Internal'},
            },
            {
                'id': 'owa-technical',
                'stage': 'validate',
                'agent': 'Outcome Verifier',
                'title': 'Technical access probe passed',
                'summary': 'Exchange resolves the delegated mailbox for the requester and returns a healthy OWA access endpoint.',
                'skill': 'mailbox_access_probe',
                'system': 'Exchange Online',
                'connector': 'M365 MCP Server',
                'duration': '1.1 s',
                'command': 'Test-MailboxDelegation -Protocol OWA',
                'request': {'mailbox': 'finance.operations@contoso.com', 'delegate': 'avery.morgan@contoso.com'},
                'response': {'authorization': 'Granted', 'mailbox_resolved': True, 'endpoint': 'Healthy'},
                'evidence': ['Delegate token resolves mailbox', 'OWA endpoint healthy', 'No conditional access block'],
                'policy': {'identity': 'outcome-verifier', 'authorization': 'synthetic.validate', 'data_class': 'Confidential'},
            },
            {
                'id': 'user-confirmation',
                'stage': 'validate',
                'agent': 'Approval Manager',
                'title': 'Requester confirmation required',
                'summary': 'The requester receives a Teams card with the verified mailbox and permission details before ticket closure.',
                'skill': 'user_confirmation_gate',
                'system': 'Teams / Copilot Studio',
                'connector': 'Microsoft Graph',
                'duration': 'Human response',
                'command': 'POST /chats/avery.morgan/messages',
                'request': {'template': 'mailbox_access_confirmation', 'change_id': 'EXO-772910'},
                'response': {'state': 'Awaiting confirmation', 'message_id': 'MSG-55218', 'checkpoint': 'cp-004'},
                'evidence': ['Technical validation attached', 'Requester identity verified', 'Closure paused at cp-004'],
                'policy': {'identity': 'approval-manager', 'authorization': 'confirmation.request', 'data_class': 'Internal'},
                'gate': {
                    'kind': 'confirmation',
                    'eyebrow': 'HUMAN CONTROL POINT 2 OF 2',
                    'title': 'Requester access confirmation',
                    'message': 'Avery Morgan confirms that Finance Operations opens successfully in Outlook on the web.',
                    'recipient': 'Avery Morgan / Requester',
                    'channel': 'Teams chat / MSG-55218',
                    'primary': 'Access confirmed',
                    'secondary': 'Access still blocked',
                },
            },
            {
                'id': 'close',
                'stage': 'resolve',
                'agent': 'ServiceNow Agent',
                'title': 'Evidence written and request closed',
                'summary': 'Approval, Exchange change evidence, propagation probes, and user confirmation are written to the request before closure.',
                'skill': 'update_work_notes + close_ticket',
                'system': 'ServiceNow',
                'connector': 'ServiceNow MCP Server',
                'duration': '524 ms',
                'command': 'PATCH /api/now/table/sc_req_item/7f2c91d5db43a110',
                'request': {'state': 'Closed Complete', 'close_code': 'Solved Remotely', 'evidence_count': 12},
                'response': {'closed': True, 'state': 'Closed Complete', 'version': 11, 'sla_breached': False},
                'evidence': ['Work notes contain correlated evidence', 'User confirmation MSG-55218 linked', 'SLA target met'],
                'policy': {'identity': 'svc-mailbox-agent', 'authorization': 'ticket.close', 'data_class': 'Internal'},
                'final': True,
            },
        ],
    },
    'access': {
        'label': 'Shared Mailbox Access Issue',
        'short_label': 'Access issue',
        'kicker': 'INCIDENT / DIAGNOSE AND REMEDIATE',
        'description': 'Isolate an Outlook-only access failure, repair delegation, verify propagation, and confirm recovery.',
        'incident': {
            'number': 'INC0086342',
            'type': 'Incident',
            'priority': 'P2 - High',
            'state': 'New',
            'created': '09:17:44 UTC',
            'assignment_group': 'Messaging Operations',
            'summary': 'Sales Operations shared mailbox no longer appears in Outlook',
            'mailbox': 'sales.operations@contoso.com',
            'requester': 'Jordan Lee',
            'requester_upn': 'jordan.lee@contoso.com',
            'owner': 'Morgan Chen',
            'permission': 'Full Access + Send As',
            'target_sla': '60 min',
        },
        'run': {
            'id': 'RUN-ACC-42D91B',
            'correlation_id': 'corr-9aa2-6f42-81ce',
            'policy': 'SMB-ACCESS-RECOVERY-v2.9',
            'risk': 'Medium',
        },
        'stages': [
            {'id': 'trigger', 'label': 'Trigger'},
            {'id': 'intake', 'label': 'Intake'},
            {'id': 'reason', 'label': 'Diagnose'},
            {'id': 'secure', 'label': 'Secure'},
            {'id': 'execute', 'label': 'Remediate'},
            {'id': 'wait', 'label': 'Propagate'},
            {'id': 'validate', 'label': 'Validate'},
            {'id': 'resolve', 'label': 'Resolve'},
        ],
        'steps': [
            {
                'id': 'incident-event',
                'stage': 'trigger',
                'agent': 'Integration Layer',
                'title': 'Incident event accepted',
                'summary': 'The signed ServiceNow webhook is normalized and delivered once to the production mailbox-agent queue.',
                'skill': 'servicenow_event_listener',
                'system': 'ServiceNow',
                'connector': 'Logic Apps + Service Bus',
                'duration': '201 ms',
                'command': 'POST /events/servicenow/v1/incidents',
                'request': {'sys_id': 'ae219bb87f901011', 'number': 'INC0086342', 'event': 'incident.created'},
                'response': {'accepted': True, 'queue': 'mailbox-operations-prod', 'sequence': 18457},
                'evidence': ['HMAC signature verified', 'Duplicate event check passed', 'Queue delivery acknowledged'],
                'policy': {'identity': 'svc-snow-webhook', 'authorization': 'event.ingest', 'data_class': 'Internal'},
            },
            {
                'id': 'incident-intake',
                'stage': 'intake',
                'agent': 'ServiceNow Agent',
                'title': 'Incident claimed and enriched',
                'summary': 'The agent assigns the incident, reads affected-user context, and correlates the mailbox from the configuration item.',
                'skill': 'intent_classification',
                'system': 'ServiceNow',
                'connector': 'ServiceNow MCP Server',
                'duration': '488 ms',
                'command': 'PATCH /api/now/table/incident/ae219bb87f901011',
                'request': {'assigned_to': 'Shared Mailbox Agent', 'state': 'In Progress', 'priority': 2},
                'response': {'updated': True, 'mailbox_ci': 'sales.operations@contoso.com', 'required_fields': '7/7'},
                'evidence': ['Exclusive processing lock acquired', 'Mailbox CI resolved', 'P2 policy selected'],
                'policy': {'identity': 'mi-mailbox-agent-prod', 'authorization': 'ticket.write', 'data_class': 'Internal'},
            },
            {
                'id': 'access-classify',
                'stage': 'reason',
                'agent': 'LLM Ticket Classifier',
                'title': 'Access failure classified',
                'summary': 'The classifier distinguishes an existing-access incident from a new delegation request and selects the recovery workflow.',
                'skill': 'classify_and_extract',
                'system': 'Azure OpenAI',
                'connector': 'Private Endpoint',
                'duration': '684 ms',
                'command': 'responses.create(model=gpt-4.1, schema=MailboxIntent)',
                'request': {'ticket': 'INC0086342', 'taxonomy': 'shared_mailbox.v3', 'redaction': 'enabled'},
                'response': {'intent': 'shared_mailbox.access.failure', 'confidence': 0.96, 'remediation': 'permission_repair'},
                'evidence': ['Structured output schema valid', 'Existing entitlement detected in text', 'Recovery policy selected'],
                'policy': {'identity': 'mi-agent-runtime', 'authorization': 'aoai.inference', 'data_class': 'Internal'},
            },
            {
                'id': 'access-plan',
                'stage': 'reason',
                'agent': 'Root Agent',
                'title': 'Diagnostic plan checkpointed',
                'summary': 'The orchestrator orders read-only checks before mutation and registers permission restore as the rollback action.',
                'skill': 'plan_workflow',
                'system': 'Agent Runtime',
                'connector': 'Microsoft Agent Framework',
                'duration': '102 ms',
                'command': 'orchestrator.plan(policy="SMB-ACCESS-RECOVERY-v2.9")',
                'request': {'intent': 'shared_mailbox.access.failure', 'priority': 'P2', 'mutation_after_diagnosis': True},
                'response': {'steps': 9, 'gates': 2, 'checkpoint': 'cp-101', 'rollback': 'permission_restore'},
                'evidence': ['Read-before-write order enforced', 'Recovery command is allowlisted', 'Checkpoint cp-101 committed'],
                'policy': {'identity': 'root-agent', 'authorization': 'workflow.execute', 'data_class': 'Internal'},
            },
            {
                'id': 'access-pim',
                'stage': 'secure',
                'agent': 'Remediation Agent',
                'title': 'Exchange role activated',
                'summary': 'The managed remediation identity activates Exchange Administrator with the incident number as justification.',
                'skill': 'pim_activate',
                'system': 'Microsoft Entra',
                'connector': 'Microsoft Graph',
                'duration': '3.0 s',
                'command': 'POST /roleManagement/directory/roleAssignmentScheduleRequests',
                'request': {'role': 'Exchange Administrator', 'duration': 'PT1H', 'justification': 'INC0086342'},
                'response': {'status': 'Provisioned', 'expires': '10:20 UTC', 'mfa': 'satisfied'},
                'evidence': ['Eligible assignment verified', 'MFA claim present', 'Activation audit ID PIM-88467'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'eligible role', 'data_class': 'Privileged'},
            },
            {
                'id': 'access-status',
                'stage': 'reason',
                'agent': 'Remediation Agent',
                'title': 'Mailbox state and rights inspected',
                'summary': 'Exchange confirms that the mailbox is healthy and that explicit Full Access and Send As entries exist for the user.',
                'skill': 'mailbox_status_check',
                'system': 'Exchange Online',
                'connector': 'M365 MCP Server',
                'duration': '1.5 s',
                'command': 'Get-EXOMailbox + Get-EXORecipientPermission',
                'request': {'identity': 'sales.operations@contoso.com', 'trustee': 'jordan.lee@contoso.com'},
                'response': {'mailbox_state': 'Active', 'full_access': True, 'send_as': True, 'automapping': 'Unknown'},
                'evidence': ['Mailbox is active', 'Full Access ACE present', 'Send As ACE present'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'exchange.read', 'data_class': 'Confidential'},
            },
            {
                'id': 'owa-check',
                'stage': 'validate',
                'agent': 'Approval Manager',
                'title': 'OWA isolation check requested',
                'summary': 'The user tests direct mailbox access in Outlook on the web to separate service-side authorization from desktop caching.',
                'skill': 'user_confirmation_gate',
                'system': 'Teams / Outlook Web',
                'connector': 'Microsoft Graph',
                'duration': 'Human response',
                'command': 'POST /chats/jordan.lee/messages',
                'request': {'template': 'owa_isolation_test', 'mailbox': 'sales.operations@contoso.com'},
                'response': {'state': 'Awaiting result', 'message_id': 'MSG-55807', 'checkpoint': 'cp-102'},
                'evidence': ['OWA test URL generated', 'User identity matched incident', 'Workflow paused at cp-102'],
                'policy': {'identity': 'approval-manager', 'authorization': 'confirmation.request', 'data_class': 'Internal'},
                'gate': {
                    'kind': 'diagnostic',
                    'eyebrow': 'DIAGNOSTIC CONTROL POINT 1 OF 2',
                    'title': 'OWA isolation result',
                    'message': 'Jordan Lee reports whether Sales Operations opens directly in Outlook on the web.',
                    'recipient': 'Jordan Lee / Affected user',
                    'channel': 'Teams chat / MSG-55807',
                    'primary': 'OWA access works',
                    'secondary': 'OWA also blocked',
                },
            },
            {
                'id': 'automapping-check',
                'stage': 'reason',
                'agent': 'Remediation Agent',
                'title': 'Stale Auto-Mapping state identified',
                'summary': 'Because OWA succeeds, the agent narrows the failure to Outlook Auto-Mapping and finds a stale delegate backlink.',
                'skill': 'outlook_cache_check',
                'system': 'Exchange Online',
                'connector': 'Exchange PowerShell via MCP',
                'duration': '1.2 s',
                'command': 'Get-MailboxPermission + Get-ADUser msExchDelegateListLink',
                'request': {'mailbox': 'sales.operations@contoso.com', 'delegate': 'jordan.lee@contoso.com'},
                'response': {'owa': 'Healthy', 'automapping': 'Stale', 'delegate_backlink': 'Missing', 'repair_recommended': True},
                'evidence': ['Service-side access succeeds', 'Outlook-only scope confirmed', 'Auto-Mapping backlink mismatch found'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'exchange.read', 'data_class': 'Confidential'},
            },
            {
                'id': 'permission-repair',
                'stage': 'execute',
                'agent': 'Remediation Agent',
                'title': 'Delegation removed and re-added',
                'summary': 'The agent executes the approved recovery runbook, preserving Send As while refreshing Full Access and Auto-Mapping.',
                'skill': 'permission_remove_readd',
                'system': 'Exchange Online',
                'connector': 'Exchange PowerShell via MCP',
                'duration': '4.6 s',
                'command': 'Remove-MailboxPermission; Add-MailboxPermission -AutoMapping $true',
                'request': {'identity': 'sales.operations@contoso.com', 'user': 'jordan.lee@contoso.com', 'preserve': ['SendAs']},
                'response': {'removed': True, 'readded': True, 'automapping': True, 'change_id': 'EXO-773104'},
                'evidence': ['Recovery runbook RA-MBX-07 authorized', 'Existing rights snapshot retained', 'Exchange change ID captured'],
                'policy': {'identity': 'cna-mailbox-remediator', 'authorization': 'exchange.write.scoped', 'data_class': 'Privileged'},
            },
            {
                'id': 'access-replication',
                'stage': 'wait',
                'agent': 'Remediation Agent',
                'title': 'Permission propagation monitored',
                'summary': 'The durable workflow waits without holding compute and probes until the refreshed delegation is globally effective.',
                'skill': 'replication_wait',
                'system': 'Agent Runtime',
                'connector': 'Durable checkpoint',
                'duration': '20 min policy',
                'delay': 1700,
                'command': 'wait.until(automapping_effective, interval="PT2M", timeout="PT20M")',
                'request': {'change_id': 'EXO-773104', 'probe_interval': 'PT2M', 'timeout': 'PT20M'},
                'response': {'effective': True, 'probes': 4, 'elapsed': 'PT8M03S', 'checkpoint': 'cp-103'},
                'evidence': ['Worker released during wait', 'Four propagation probes recorded', 'Auto-Mapping backlink now present'],
                'policy': {'identity': 'root-agent', 'authorization': 'workflow.resume', 'data_class': 'Internal'},
            },
            {
                'id': 'access-verify',
                'stage': 'validate',
                'agent': 'Outcome Verifier',
                'title': 'Recovery state verified',
                'summary': 'An independent read confirms Full Access, Send As, Auto-Mapping, and mailbox health after propagation.',
                'skill': 'permission_verify',
                'system': 'Exchange Online',
                'connector': 'M365 MCP Server',
                'duration': '1.0 s',
                'command': 'Test-MailboxDelegation -IncludeAutoMapping',
                'request': {'mailbox': 'sales.operations@contoso.com', 'delegate': 'jordan.lee@contoso.com'},
                'response': {'full_access': True, 'send_as': True, 'automapping': True, 'mailbox_health': 'Healthy'},
                'evidence': ['Independent read-after-write passed', 'All expected permissions match', 'No conflicting deny entry'],
                'policy': {'identity': 'outcome-verifier', 'authorization': 'exchange.read', 'data_class': 'Confidential'},
            },
            {
                'id': 'access-confirmation',
                'stage': 'validate',
                'agent': 'Approval Manager',
                'title': 'Final user validation requested',
                'summary': 'The user receives the recovery evidence and confirms that the mailbox has returned to the Outlook profile.',
                'skill': 'user_confirmation_gate',
                'system': 'Teams / Outlook',
                'connector': 'Microsoft Graph',
                'duration': 'Human response',
                'command': 'POST /chats/jordan.lee/messages',
                'request': {'template': 'outlook_recovery_confirmation', 'change_id': 'EXO-773104'},
                'response': {'state': 'Awaiting confirmation', 'message_id': 'MSG-55862', 'checkpoint': 'cp-104'},
                'evidence': ['Recovery evidence attached', 'Outlook validation steps delivered', 'Closure paused at cp-104'],
                'policy': {'identity': 'approval-manager', 'authorization': 'confirmation.request', 'data_class': 'Internal'},
                'gate': {
                    'kind': 'confirmation',
                    'eyebrow': 'HUMAN CONTROL POINT 2 OF 2',
                    'title': 'Outlook recovery confirmation',
                    'message': 'Jordan Lee confirms that Sales Operations is visible and opens normally in Outlook.',
                    'recipient': 'Jordan Lee / Affected user',
                    'channel': 'Teams chat / MSG-55862',
                    'primary': 'Access restored',
                    'secondary': 'Issue persists',
                },
            },
            {
                'id': 'incident-close',
                'stage': 'resolve',
                'agent': 'ServiceNow Agent',
                'title': 'Incident resolved with evidence',
                'summary': 'Diagnostic findings, the controlled repair, propagation checks, and user confirmation are written before resolution.',
                'skill': 'update_work_notes + close_ticket',
                'system': 'ServiceNow',
                'connector': 'ServiceNow MCP Server',
                'duration': '581 ms',
                'command': 'PATCH /api/now/table/incident/ae219bb87f901011',
                'request': {'state': 'Resolved', 'close_code': 'Configuration restored', 'evidence_count': 14},
                'response': {'resolved': True, 'state': 'Resolved', 'version': 13, 'sla_breached': False},
                'evidence': ['Root cause documented as stale Auto-Mapping', 'User confirmation MSG-55862 linked', 'P2 SLA target met'],
                'policy': {'identity': 'svc-mailbox-agent', 'authorization': 'ticket.resolve', 'data_class': 'Internal'},
                'final': True,
            },
        ],
    },
}